name: Python Tests

# Trigger the workflow on push or pull request
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies (for PySide6)
        run: sudo apt-get install -y libxkbcommon-x11-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PySide6==6.7.2 fitspy==2024.5 ==3.1.5 pandas==2.2.3 matplotlib==3.8.4 seaborn==0.13.2 markdown==3.7 lmfit superqt


      - name: installed packages
        run: |
          pip list  

      - name: Run tests
        run: |
          python -m pytest tests/