name: Python Tests

# Trigger the workflow on push or pull request
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies (for PySide6)
        run: sudo apt-get install -y libxkbcommon-x11-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PySide6
          python -m pip install pytest

      - name: Run tests
        run: |
          python -m pytest tests/